# Generated by Django 5.0.4 on 2024-04-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('born_date', models.CharField(default=None, max_length=25)),
                ('born_location', models.CharField(default=None, max_length=40)),
                ('decsription', models.CharField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quotes_app.author', to_field='name')),
                ('tag', models.ManyToManyField(to='quotes_app.tag')),
            ],
        ),
    ]
