# Generated by Django 5.0.4 on 2024-04-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_author_tag_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quotes_app.author', to_field='name'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quotes_app.tag', to_field='name'),
        ),
    ]
