# Generated by Django 5.0.4 on 2024-04-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_alter_quote_author_alter_quote_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tag',
        ),
        migrations.AddField(
            model_name='quote',
            name='tag',
            field=models.ManyToManyField(to='quotes_app.tag'),
        ),
    ]
