# Generated by Django 5.0.4 on 2024-04-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0004_remove_quote_tag_quote_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born_date',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='author',
            name='born_location',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='author',
            name='decsription',
            field=models.CharField(default=None),
        ),
    ]
