# Generated by Django 5.0.4 on 2024-04-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0005_author_born_date_author_born_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
